const ContentListActionTypes = {
  ON_FETCHING_LIST: "ON_FETCHING_LIST",
  ON_SEARCH: "ON_SEARCH",
  SET_CONTENT_LIST: "SET_CONTENT_LIST",
  SET_SEARCHED_CONTENT_LIST: "SET_SEARCHED_CONTENT_LIST",
  SET_ERROR: "SET_ERROR",
};

export default ContentListActionTypes;
